New Step description
bitrise-steplib/bitrise-step-android-build pull request #21
Opened 2020-11-11 15:14 UTC by zoltan-baba

2020-11-19 12:41 UTC, BirmacherAkos requested changes
Please check my comments

2020-11-19 12:41 UTC, BirmacherAkos commented on step.yml
> +     You can find the available variants in Android Studio. If you leave the input empty, the Step will use the default variant that is set when you add your project to Bitrise.
That's not true.
The default value of the Variant and the Module is empty: `""`
https://github.com/bitrise-steplib/bitrise-step-android-build/pull/21/files#diff-6bc88361fc7fca6b922fde7f3243d0e3815d0584b5493c16dc45633b36172529R84

https://github.com/bitrise-steplib/bitrise-step-android-build/pull/21/files#diff-6bc88361fc7fca6b922fde7f3243d0e3815d0584b5493c16dc45633b36172529L41

2020-11-19 14:38 UTC, BirmacherAkos approved these changes

2020-12-09 16:19 UTC, lpusok approved these changes

2020-12-09 16:20 UTC, merged